### ISSUE TITLE
cPanel installation GUIDE

### ISSUE THREAD

**Issue by danielrodrigotest** [oussamatn/radio-player#5]
Hi, I found amazing your code. However, your installation guide was not clear at all. I would like to suggest instructions for installing into subdomains with the Azuracast's API. Thanks!!!!

**Comment by oussamatn** [comment]
Hi, 
To run this project on a shared hosting environment you'll need to clone it locally. Then make your modifications into your configuration file. 

Once everything is done, go to the command line then run : ```npm run build``` . This will create a new folder ```dist``` with all static files and assets. 

The next step is to copy this folder into your shared hosting server.

Example: if you are using CPanel then create a new subdomain with new folder. Copy all dist content to the dist content to this folder. 

Sometimes you'll rum into a few 404 errors. To resolve this problem I suggest to add a .htaccess file with this configuration: 
```

<IfModule mod_rewrite.c>
  RewriteEngine On
  RewriteBase /
  RewriteRule ^index\.html$ - [L]
  RewriteCond %{REQUEST_FILENAME} !-f
  RewriteCond %{REQUEST_FILENAME} !-d
  RewriteRule . /index.html [L]
</IfModule>

```
