### ISSUE TITLE
Addition charsets are not aviable

### ISSUE THREAD

**Issue by cyb3rm4n** [oussamatn/radio-player#7]
Testing the web app after cloning and adding my own station API link. As relust i have the next error:

For your own testing you can use my API link: https://air.waveradio.ru/api

Russian and japanese names on the track names are not showing, if the track name is on russian, then script writes the N/A. Igf traclk has many non-latin symbools and ONLY 1 x letter, then opnl;y x letter is shown on the track name.
![изображение](https://user-images.githubusercontent.com/1812907/141695994-5b25fe04-f2e4-4598-a41d-8cec9017208b.png)

**Comment by oussamatn** [comment]
Thank you for reporting this bug. 

Fixed [394cb333982d8ee994d3a070a1a90fd48c9c3cdb]
