### ISSUE TITLE
Refresh station page

### ISSUE THREAD

**Issue by rogeroffer** [oussamatn/radio-player#9]
Refresh station page 404 error not found

**Comment by oussamatn** [comment]
Can you describe your environment ?
Are you running on docker-compose ?

**Comment by rogeroffer** [comment]
Not using docker. Go to https://ddope.sslstreaming.com and open a station try to refresh it, it will give you 404 error not found. Same on pwa app on pull down reload.

**Comment by oussamatn** [comment]
You need to add a `.htaccess ` file and redirect all requests to `index.html`
Here's an example :
```
<IfModule mod_rewrite.c>
  RewriteEngine On
  RewriteBase /
  RewriteRule ^index\.html$ - [L]
  RewriteCond %{REQUEST_FILENAME} !-f
  RewriteCond %{REQUEST_FILENAME} !-d
  RewriteRule . /index.html [L]
</IfModule>
```

**Comment by oussamatn** [comment]
@rogeroffer I see that you fixed the problem.
